services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StefanFroemken\PleskWidget\:
    resource: '../Classes/*'
    exclude: '../Classes/Widget/*'

  dashboard.widget.plesk.webspace:
    class: 'StefanFroemken\PleskWidget\Widget\WebspaceWidget'
    arguments:
      $dataProvider: '@StefanFroemken\PleskWidget\DataProvider\WebspaceDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'plesk.webspace'
        groupNames: 'systemInfo'
        title: 'Plesk Webspace'
        description: 'Show used and available diskspace'
        iconIdentifier: 'ext-plesk-widget-icon'
        height: 'medium'

  dashboard.widget.plesk.server:
    class: 'StefanFroemken\PleskWidget\Widget\ServerWidget'
    arguments:
      $dataProvider: '@StefanFroemken\PleskWidget\DataProvider\ServerDataProvider'
    tags:
      - name: dashboard.widget
        identifier: 'plesk.server'
        groupNames: 'systemInfo'
        title: 'Plesk Server Information'
        description: 'Show server related information and login link'
        iconIdentifier: 'ext-plesk-widget-icon'
        height: 'medium'

  dashboard.widget.plesk.php:
    class: 'StefanFroemken\PleskWidget\Widget\PhpWidget'
    tags:
      - name: dashboard.widget
        identifier: 'plesk.php'
        groupNames: 'systemInfo'
        title: 'Plesk PHP Settings'
        description: 'Show PHP related information'
        iconIdentifier: 'ext-plesk-widget-icon'
        height: 'medium'

  StefanFroemken\PleskWidget\Configuration\ExtConf:
    factory: ['@StefanFroemken\PleskWidget\Configuration\ExtConfFactory', 'create']

  StefanFroemken\PleskWidget\Service\PleskSiteService:
    arguments:
      $cache: '@cache.runtime'
