name: Tests

on: pull_request

jobs:
  CGL:
    name: Coding Style Check (TYPO3 Community CGL)

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Composer'
        run: Build/Scripts/runTests.sh -p 8.1 -s composerUpdate

      - name: 'Lint PHP'
        run: Build/Scripts/runTests.sh -p 8.1 -s lint

      - name: 'Validate code against CGL'
        run: Build/Scripts/runTests.sh -p 8.1 -s cgl -n

      - name: 'Execute functional tests'
        run: Build/Scripts/runTests.sh -p 8.1 -d sqlite -s functional
